# -*- coding: utf-8 -*-
"""MNIST0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WsCJjChJImAhtGNcHzp3kiXNU4uqE4LV
"""

!pip install livelossplot

from fastai.vision.all import *
import torchvision
import torchvision.transforms as transforms
from livelossplot import PlotLosses

URLs.MNIST

cfg = fastai_cfg()
cfg.data, cfg.path('data')

fastai_path('/content/')

path = untar_data(URLs.MNIST, c_key="data")
Path.BASE_PATH = path
path.ls()

(path/"training").ls()

image = Image.open((path/"training/8").ls()[0])
image

image.mode

block = DataBlock(blocks=(ImageBlock, CategoryBlock), get_items=get_image_files, \
                  splitter=RandomSplitter(valid_pct=0.2, seed=42), get_y=parent_label, \
                  batch_tfms=aug_transforms(mult=2., do_flip=False))

loaders = block.dataloaders(path/'training')
loaders.train.show_batch(max_n=4, nrows=1)

learn = cnn_learner(loaders, resnet34, metrics=accuracy)

learn.lr_find()

learn.fine_tune(12, base_lr=0.00251, cbs=[ShowGraphCallback()])